# Generated by Django 2.2.28 on 2023-08-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cder2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jfhf', models.BigIntegerField()),
                ('rewt', models.BigIntegerField()),
            ],
        ),
    ]
