# Generated by Django 2.2.28 on 2023-08-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cder3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cder4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hfhfh', models.BigIntegerField()),
                ('teyey', models.BigIntegerField()),
            ],
        ),
    ]
